// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQgi78bqkv32U5mCxCV8I5iV2Z7_d-ASU',
    appId: '1:820529154357:android:da9d85274a5be113dba47c',
    messagingSenderId: '820529154357',
    projectId: 'eformulae-bf8cf',
    databaseURL: 'https://eformulae-bf8cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eformulae-bf8cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCe6a1eNbpttMI5POmD7HTD97NKqQH_c',
    appId: '1:820529154357:ios:dab0253c0128bf74dba47c',
    messagingSenderId: '820529154357',
    projectId: 'eformulae-bf8cf',
    databaseURL: 'https://eformulae-bf8cf-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eformulae-bf8cf.appspot.com',
    androidClientId: '820529154357-65hmpn9ucmjc4frqvm5vhhq3mgc7inhi.apps.googleusercontent.com',
    iosClientId: '820529154357-kgn32fpm70tt5vfsfokiclq5q6rc9vfe.apps.googleusercontent.com',
    iosBundleId: 'com.mindberzerk.eformula',
  );

}